name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    run-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodby
        run: echo "Done - bye!"
